services:

  db:
    image: mysql:8.0
    container_name: mysql_test
    networks:
      - api-common-net
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "db_data:/var/lib/mysql"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: drf_api
    container_name: api_worker
    networks:
      - api-common-net
    depends_on:
      - db
    env_file: .env
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"


volumes:
  db_data:

networks:
  api-common-net:
    driver: bridge