services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    container_name: mysql_test
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - "mysql_data:/var/lib/mysql"

volumes:
  mysql_data: