# Generated by Django 5.0.6 on 2024-07-01 04:24

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=18, default=Decimal('0.0'), max_digits=36,
                                                validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=18, unique=True,
                                          validators=[django.core.validators.MinLengthValidator(18)])),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions',
                                             to='restapi.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'indexes': [models.Index(fields=['txid'], name='restapi_tra_txid_89f30c_idx'),
                            models.Index(fields=['wallet'], name='restapi_tra_wallet__1abf71_idx')],
            },
        ),
    ]
